server:
  port: 8082
  servlet:
    context-path: /catalogs
spring:
  application:
    name: catalog-service
  data:
    mongodb:
      database: inventory
      port: 27017
  datasource:
    url: jdbc:postgresql://localhost:5432/restcommerce
    username: postgres
    password: root
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/