server:
  port: ${CATALOG_PORT:8085}
  servlet:
    context-path: /catalogs
spring:
  data:
    mongodb:
      database: inventory
      port: 27017
  application:
    name: catalog-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
