server:
  port: 8080
  error:
    include-message: always
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  # GATEWAY CONFIG
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventories/**
            - Header=Authorization
          filters:
            - AuthenticationFilter

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalogs/**
            - Header=Authorization
          filters:
            - AuthenticationFilter

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
            - Header=Authorization
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
            - Header=Authorization
          filters:
            - AuthenticationFilter

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
            - Header=Authorization
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
