server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  # GATEWAY CONFIG
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventories/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalogs/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

eureka:
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
