server:
  port: 8085
  servlet:
    context-path: /payments
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/restcommerce
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update