server:
  port: ${INVENTORY_PORT:8081}
  servlet:
    context-path: /inventories
spring:
  data:
    mongodb:
      database: inventory
      port: 27017
  application:
    name: inventory-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
