server:
  port: 8086
  servlet:
    context-path: /inventories
spring:
  data:
  application:
    name: inventory-service
    mongodb:
      database: inventory
      port: 27017
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/