server:
  port: 8082
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/restcommerce
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
