server:
  port: 8083
  servlet:
    context-path: /carts
spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://localhost:5432/restcommerce
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/